<a href="https://colab.research.google.com/github/soniapachecomza/python-practica/blob/main/Organizando_DataFrames_(Sort).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
data = [[1,2,3], [4,5,6], [7,8,9]]
data

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [5]:
list('235')

['2', '3', '5']

['2', '3', '5']

In [7]:
df = pd.DataFrame(data, list('321'), list('ZXY'))
df

   Z  X  Y
3  1  2  3
2  4  5  6
1  7  8  9

In [10]:
df.sort_index(inplace = True)
df

   Z  X  Y
1  7  8  9
2  4  5  6
3  1  2  3

In [11]:
df.sort_index(inplace = True, axis = 1)
df

   X  Y  Z
1  8  9  7
2  5  6  4
3  2  3  1

In [14]:
df.sort_values(by = 'X', inplace = True)
df

   X  Y  Z
3  2  3  1
2  5  6  4
1  8  9  7

In [15]:
df.sort_values(by = '3', axis = 1, inplace = True)
df

   Z  X  Y
3  1  2  3
2  4  5  6
1  7  8  9

In [16]:
df.sort_index()
df.sort_index(axis = 1)
df

   Z  X  Y
3  1  2  3
2  4  5  6
1  7  8  9